USE `wecare`;
DROP TABLE IF exists `appointments`;
DROP TABLE IF exists `allergens_users`;
DROP TABLE IF exists `medecines_allergens`;
DROP TABLE IF exists `medecines_prescriptions`;
DROP TABLE IF exists `allergens`;
DROP TABLE IF exists `practitioners`;
DROP TABLE IF exists `customers`;
DROP TABLE IF exists `users`;
DROP TABLE IF exists `medecines`;
DROP TABLE IF exists `prescriptions`;